### PR TITLE
Smart Look Around

### PR DESCRIPTION
**Pull request by oleflb**
## Introduced Changes

* Runs a look around action for at most 6 seconds, but aborts as soon as localization converged to only 1 hypothesis

Fixes #

## ToDo / Known Issues

*If this is a WIP describe which problems are to be fixed.*

## Ideas for Next Iterations (Not This PR)

* Clean up look_around.rs

## How to Test

*Describe how to test your changes. (For the reviewer)*

### CODE REVIEW

**Review by schluis — CHANGES_REQUESTED** [review]
I like!

**Comment by schluis** [comment]
Somehow, the interpolation between Penalized and Standing with HeadMotion doesn't work correctly. The head snaps to the left when entering `Standing`
image

**Comment by oleflb** [comment]
> Somehow, the interpolation between Penalized and Standing with HeadMotion doesn't work correctly. The head snaps to the left when entering `Standing` image

I believe the dispatching interpolator doesn't take into account head motions. So this is a feature we don't have

**Comment by oleflb** [comment]
@knoellle I need help with the behavior simulator. Where do I need to add something

**Comment by knoellle** [comment]
Probably need to add an output in the FakeData node.

**Comment by oleflb** [comment]
@schluis the behavior simulator error is now fixed.

**Comment by oleflb** [comment]
@schluis head motion velocity is fixed now. There was an issue in the head_motion node :)

**Review by schluis — APPROVED** [review]
I like 👍🏻

**Pull request merged**
