### PR TITLE
Add engineering documentation

### PR DESCRIPTION
**Pull request by h3ndrk**
## Introduced Changes

This PR adds first engineering documentation. Will be discussed in the next Dev-Meeting.

## ToDo / Known Issues

None

## Ideas for Next Iterations (Not This PR)

None

## How to Test

Check if the MkDocs site renders successfully.

### CODE REVIEW

**Comment by schluis** [comment]
I like the idea for big changes, but it may create a lot of overhead when reviewing is needed after every step.

**Comment by h3ndrk** [comment]
> I like the idea for big changes, but it may create a lot of overhead when reviewing is needed after every step.

The idea is to only document the target where we want to get to for the long term timespan (strategy). We will get there slowly step-by-step (tactic). The intention is to have more benefits than overhead from this. I will explain the strategy and tactic in the next Dev-Meeting and we can discuss if and how we want to make the first steps.

**Comment by schmidma** [comment]
I don't know whether it is any helpful, but this is the response of ChatGPT ;)



Overall, your text is a good starting point to define your software engineering approach, but it could benefit from some clarifications and additional details. Here are some suggestions:

    Start by defining your software development process in more detail. For example, you could use an Agile methodology such as Scrum or Kanban, or a more traditional approach such as Waterfall or V-Model. This will help you establish clear roles, responsibilities, and workflows for your team.
    Emphasize the importance of collaboration and communication within your team. Make sure everyone is on the same page regarding the project goals, requirements, and design decisions. Use tools such as code reviews, pair programming, and regular team meetings to ensure that everyone is aligned.
    Clarify your definition of "high quality and correct software". What are your quality criteria? How will you measure them? For example, you could define metrics such as code coverage, bug density, and user satisfaction, and track them over time.
    Provide more details on your testing strategy. How will you ensure that your software is functional, reliable, and performant? Will you use automated testing, manual testing, or a combination of both? What types of tests will you perform (e.g., unit tests, integration tests, acceptance tests)?
    Consider adopting a continuous integration and deployment (CI/CD) approach. This will allow you to automate your build, test, and deployment processes, and ensure that your software is always in a releasable state. Use tools such as Jenkins, Travis CI, or CircleCI to implement your CI/CD pipeline.
    Finally, make sure to document your software development process and keep it up-to-date. Use a wiki, a document repository, or a project management tool such as Jira to store your project artifacts (e.g., requirements, design documents, test cases) and track your progress.

Here's an improved version of your text:

The Team HULKs are committed to delivering high-quality and correct software for playing soccer at RoboCup. To achieve this goal, we follow a well-defined software development process that emphasizes collaboration, communication, and continuous improvement. Our process consists of the following phases:

    Requirements: In this phase, we define the problem we want to solve and the requirements that our software should meet. We carefully evaluate the cost and benefits of each requirement and make sure they are aligned with our project goals.
    Design: In this phase, we create a detailed design that specifies the components of our software, their properties, and their interactions. We also select the data structures and algorithms that we will use, and create an implementation plan that outlines the development tasks and milestones. We make sure to test our design and validate it against our requirements before moving to the next phase.
    Construction: In this phase, we implement our design and write tests to ensure that our code is correct and robust. We also measure our code quality and performance and make improvements as needed. We use version control to track our code changes and ensure that our software is always in a releasable state.
    Evaluation: In this phase, we evaluate our software against our requirements and make sure that it meets our quality criteria. We also gather feedback from our users and stakeholders and use it to improve our software in future iterations.

Throughout the software development process, we emphasize collaboration and communication within our team. We use code reviews, pair programming, and team meetings to ensure that everyone is aligned and working towards our project goals. We also use automated testing and continuous integration and deployment (CI/CD) to streamline our development process and ensure that our software is always in a releasable state.

Finally, we document our software development process and keep it up-to-date. We use a wiki to store our project artifacts and track our progress, and make sure to regularly review and update our documentation to reflect any changes to our process or requirements.

To ensure the quality of our software, we define clear quality criteria and measure them using metrics such as code coverage, bug density, and user satisfaction. We also perform various types of testing, including unit tests, integration tests, and acceptance tests, and use tools such as JUnit, Mockito, and Selenium to automate our testing process.

By following this software development process, we aim to deliver high-quality and correct software that meets our users' needs and expectations. We also strive to continuously improve our process and learn from our successes and failures.

Finally, we make sure to involve non-authors in our review process to get fresh perspectives on our artifacts and ensure that we haven't missed any important details or made any mistakes.

Overall, our software development process is designed to be flexible, iterative, and collaborative, and to adapt to the changing needs and requirements of our project.

**Comment by h3ndrk** [comment]
> I don't know whether it is any helpful, but this is the response of ChatGPT ;)

No, not really helpful because ChatGPT seems to not know anything about our repository and workflow. It proposes a lot of stuff that we already do differently and it seems to not be able to understand the linked article.

It would be way more interesting to get your personal feedback because we may agree on that we want to align with these proposed things, including you.

**Comment by h3ndrk** [comment]
> I don't know whether it is any helpful, but this is the response of ChatGPT ;)

https://news.ycombinator.com/item?id=35869011

**Review by knoellle — APPROVED** [review]
I think these are good general guidelines to use when developing larger features.

**Comment by jonathan-hellwig** [comment]
I like these guidlines too. I think we could make a check list with them.

**Comment by h3ndrk** [comment]
Thanks for your feedback. Let's try that approach out and adjust if needed. :muscle:

**Pull request merged**
