### PR TITLE
Drop all obstacle hypotheses when unpenalized (without PrimaryStateTransition)

### PR DESCRIPTION
**Pull request by h3ndrk**
## Introduced Changes

Drops all obstacles in the filter, when leaving a penalty. This PR reimplements #199 without `PrimaryStateTransition`. Credit goes to Schmiddy. :muscle:

## ToDo / Known Issues

none

## Ideas for Next Iterations (Not This PR)

none

## How to Test

Use your hand to generate a sonar obstacle, press the chest button to leave penalized state, the obstacle should be removed

### CODE REVIEW

**Comment by knoellle** [comment]
The reason for implementing the original PR #199 was to avoid the robots running around phantom obstacles after a false positive obstacle detection caused by a chest button pressing hand.
Is this still relevant now that the robot looks around for five seconds before starting to move?

**Comment by h3ndrk** [comment]
I don't know how long obstacles are persisted but probably it doesn't hurt to remove them as it just makes sense. I generally like the idea to start with a fresh state (at least some relevant state) when coming back from penalized.

**Comment by knoellle** [comment]
Alright, fair point.

**Review by knoellle — APPROVED** [review]
LGTM

**Pull request merged**
