### PR TITLE
FrankenNAO 32/24

### PR DESCRIPTION
**Pull request by PasGl**
## Introduced Changes

*Describe here what this pull request does*

Fixes #

## ToDo / Known Issues

*If this is a WIP describe which problems are to be fixed.*

## Ideas for Next Iterations (Not This PR)

*If there are some improvements that could be done in a next iteration, describe them here.*

## How to Test

*Describe how to test your changes. (For the reviewer)*

### CODE REVIEW

**Review by tuxbotix — APPROVED** [review]
LGTM - merge IFF needed.

**Comment by h3ndrk** [comment]
Close or merge?

**Comment by PasGl** [comment]
Decision is up to people who have an overview on Robot Status and can tell if we need this Franken-Nao combination for much longer.

**Comment by knoellle** [comment]
Both head and body of the 24 are broken and I took the Frankennao apart.

**Pull request closed without merging**
