### PR TITLE
Fix title and remove copyright year

### PR DESCRIPTION
**Pull request by h3ndrk**
## Introduced Changes

What it says, originated from #15. The copyright year has been incremented.

## ToDo / Known Issues

None

## Ideas for Next Iterations (Not This PR)

None

## How to Test

Check the README...

### CODE REVIEW

**Comment by Bendodroid** [comment]
The GNU howto explicitly says not to do this and update the years. It also says we should have a license notice in each file and we're not doing that either so what do I even know... 

https://www.gnu.org/licenses/gpl-howto.html

**Comment by h3ndrk** [comment]
> The GNU howto explicitly says not to do this and update the years. It also says we should have a license notice in each file and we're not doing that either so what do I even know...
> 
> https://www.gnu.org/licenses/gpl-howto.html

Thanks for your answer! What a pity to have to do that manually...

**Review by julianschuler — APPROVED** [review]
LGTM!

**Comment by Bendodroid** [comment]
Slightly confusing commit message and PR title but ok 🥴

**Pull request merged**
