### PR TITLE
Update cargo dependencies to fix/ avoid some bindgen issues

### LINKED ISSUE #352: Nao camera build issue with clippy & rust analyzer
I got a rather strange issue;
This seems to be related to bindgen and once I updated bindgen and some other dependencies in `cargo.toml` the issue seems to go away.

system information:
* Fedora 38, kernel `6.2.14-300`
* `libv4l-1.22.1-5`
* rust version: `rustc 1.69.0`

```bash
[ERROR rust_analyzer::main_loop] FetchBuildDataError:
error: failed to run custom build command for `nao_camera v0.1.0 (___/hulk/crates/nao_camera)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `___/hulk/target/debug/build/nao_camera-3c3544694cfea606/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=/usr/include/linux/usb/video.h
  cargo:rerun-if-changed=/usr/include/linux/types.h
  cargo:rerun-if-changed=/usr/include/asm/types.h
  cargo:rerun-if-changed=/usr/include/asm-generic/types.h
  cargo:rerun-if-changed=/usr/include/asm-generic/int-ll64.h
  cargo:rerun-if-changed=/usr/include/asm/bitsperlong.h
  cargo:rerun-if-changed=/usr/include/asm-generic/bitsperlong.h
  cargo:rerun-if-changed=/usr/include/linux/posix_types.h
  cargo:rerun-if-changed=/usr/include/linux/stddef.h
  cargo:rerun-if-changed=/usr/include/asm/posix_types.h
  cargo:rerun-if-changed=/usr/include/asm/posix_types_64.h
  cargo:rerun-if-changed=/usr/include/asm-generic/posix_types.h
  cargo:rerun-if-changed=/usr/include/asm/bitsperlong.h
  cargo:rerun-if-changed=/usr/include/linux/uvcvideo.h
  cargo:rerun-if-changed=/usr/include/linux/ioctl.h
  cargo:rerun-if-changed=/usr/include/asm/ioctl.h
  cargo:rerun-if-changed=/usr/include/asm-generic/ioctl.h
  cargo:rerun-if-changed=/usr/include/linux/types.h
  cargo:rerun-if-changed=/usr/include/linux/videodev2.h
  cargo:rerun-if-changed=/usr/include/sys/time.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/features-time64.h
  cargo:rerun-if-changed=/usr/include/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/bits/timesize.h
  cargo:rerun-if-changed=/usr/include/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/stdc-predef.h
  cargo:rerun-if-changed=/usr/include/sys/cdefs.h
  cargo:rerun-if-changed=/usr/include/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/bits/long-double.h
  cargo:rerun-if-changed=/usr/include/gnu/stubs.h
  cargo:rerun-if-changed=/usr/include/gnu/stubs-64.h
  cargo:rerun-if-changed=/usr/include/bits/types.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/bits/timesize.h
  cargo:rerun-if-changed=/usr/include/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/bits/typesizes.h
  cargo:rerun-if-changed=/usr/include/bits/time64.h
  cargo:rerun-if-changed=/usr/include/bits/types/time_t.h
  cargo:rerun-if-changed=/usr/include/bits/types.h
  cargo:rerun-if-changed=/usr/include/bits/types/struct_timeval.h
  cargo:rerun-if-changed=/usr/include/bits/types.h
  cargo:rerun-if-changed=/usr/include/sys/select.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/bits/types.h
  cargo:rerun-if-changed=/usr/include/bits/select.h
  cargo:rerun-if-changed=/usr/include/bits/types/sigset_t.h
  cargo:rerun-if-changed=/usr/include/bits/types/__sigset_t.h
  cargo:rerun-if-changed=/usr/include/bits/types/time_t.h
  cargo:rerun-if-changed=/usr/include/bits/types/struct_timeval.h
  cargo:rerun-if-changed=/usr/include/bits/types/struct_timespec.h
  cargo:rerun-if-changed=/usr/include/bits/types.h
  cargo:rerun-if-changed=/usr/include/bits/endian.h
  cargo:rerun-if-changed=/usr/include/bits/endianness.h
  cargo:rerun-if-changed=/usr/include/bits/types/time_t.h
  cargo:rerun-if-changed=/usr/include/linux/ioctl.h
  cargo:rerun-if-changed=/usr/include/linux/types.h
  cargo:rerun-if-changed=/usr/include/linux/v4l2-common.h
  cargo:rerun-if-changed=/usr/include/linux/types.h
  cargo:rerun-if-changed=/usr/include/linux/v4l2-controls.h
  cargo:rerun-if-changed=/usr/include/linux/const.h
  cargo:rerun-if-changed=/usr/include/linux/types.h

  --- stderr
  thread 'main' panicked at '"v4l2_pix_format_union_(anonymous_at_/usr/include/linux/videodev2_h_500_2)" is not a valid Ident', /home/___/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.54/src/fallback.rs:811:9
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
     1: core::panicking::panic_fmt
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
     2: proc_macro2::fallback::validate_ident
     3: proc_macro2::fallback::Ident::_new
     4: proc_macro2::fallback::Ident::new
     5: proc_macro2::imp::Ident::new
     6: proc_macro2::Ident::new
     7: bindgen::ir::context::BindgenContext::rust_ident_raw
     8: bindgen::ir::context::BindgenContext::rust_ident
     9: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
    10: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
    11: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    12: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
    13: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
    14: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    15: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}
    16: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen
    17: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    18: bindgen::codegen::codegen::{{closure}}
    19: bindgen::ir::context::BindgenContext::gen
    20: bindgen::codegen::codegen
    21: bindgen::Bindings::generate
    22: bindgen::Builder::generate
    23: build_script_build::main
    24: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by tuxbotix**
## Introduced Changes

* Updated bindgen to avoid a problem with clippy & rust analyzer. The details are in #352.
* At the same time, I also updated some outdated dependencies.
    * `egui` parts were not updated as they seems to have more changes and same for `syn` which is a major version change, IDK if that will change the situation too much.
* Removed deprecated `fixed_slice` in algebra and use `fixed_view` as suggested.

Fixes #352

## ToDo / Known Issues
- [ ] Do we need a new SDK/ yocto build? (hula, etc?)
- [ ] Test on a NAO

## Ideas for Next Iterations (Not This PR)

- Update other dependencies which may need bigger changes.

## How to Test
I did the following & also ran with webots.

```bash
./pepsi build
./pepsi build --target nao
cargo test
cargo clippy --workspace
./twix # to verify twix compilation
# additional combinations to catch weird cases previously not caught.
./pepsi clippy --workspace 
cargo clippy --all-features
```

### CODE REVIEW

**Comment by knoellle** [comment]
Sadly this only seems to shift the error around and does not fix it.
On fedora 38, `cargo clippy --workspace` fails on main but works with these changes, but `cargo clippy --all-features` fails with the same error as #352 both on main and on this branch.

**Comment by tuxbotix** [comment]
With the changes + PR [here](https://github.com/HULKs/libv4l-rs/pull/1), I could get it to work, 

For testing, I've set `v4l = { version = "0.12.1", git = "https://github.com/tuxbotix/libv4l-rs", branch = "hulksChanges_update_bindgen" }` in this PR so auto-merging is disabled until we merge the PR to libv4l-rs

**Comment by knoellle** [comment]
There seems to be no issue running current `hulks/main` with the changes you made to `libv4l`. However, to avoid that kind of problem in the future, please create a version tag in that repo and reference the tag in our `Cargo.toml` file similar to how we handle the `egui_dock` dependency.

**Comment by tuxbotix** [comment]
What did you mean by a version tag? the current reference to `libv4l-rs` on HULKs side is to a branch not a tag so I didn't look into making a tag :D.

I can do a tag, should it be `semVer` and increment the patch number? I don't think it is a good idea to have the same tag as the original stream since it is confusing.
I prefer to do `x.y.z+hulks-1` or such a pattern if it is okay. The first part refers to the original release it is based on and the latter indicates our patch number.

**Comment by tuxbotix** [comment]
Added a tag to my fork, can switch to the hulks fork once the PR (https://github.com/HULKs/libv4l-rs/pull/1) is merged.
In that regard, this PR can be merged in either form :)

**Pull request merged**
